### ISSUE TITLE
Could not use yarn

### ISSUE THREAD

**Issue by taoqf** [Microsoft/types-publisher#359]
Steps:
1. clone [DefinitelyTyped](https://github.com/DefinitelyTyped)
2. install dependencies use [`yarn`](https://yarnpkg.com/en/)
3. run script `npm test`, then  there is an Error throws out( `npm install` works fine):
```sh
Running: git diff master~1 --name-only
types/knex/index.d.ts
Testing 2 packages: bookshelf,knex
Running with 4 processes.
Installing NPM dependencies...
Running: node /home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --installAll
module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Testing...
Testing bookshelf
	Running: node /home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --noLint
	module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Testing knex
	Running: node /home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --noLint
	module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3


=== ERRORS ===



Error in bookshelf
Command failed: node /home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --noLint
module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3


module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3


Error in knex
Command failed: node /home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --noLint
module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3


module.js:487
    throw err;
    ^

Error: Cannot find module '/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/node_modules/dtslint/bin/index.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
The following packages had errors: bookshelf, knex
Error: There was a test failure.
    at Object.<anonymous> (/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:93:9)
    at Generator.next (<anonymous>)
    at fulfilled (/home/taoqf/feidao/temp/DefinitelyTyped/node_modules/types-publisher/bin/tester/test-runner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

```

**Comment by taoqf** [comment]
It seems OK with yarn now.
