### ISSUE TITLE
Failed to install node-git under WSL

### ISSUE THREAD

**Issue by zlumer** [Microsoft/types-publisher#483]
I'm running WSL Ubuntu 18.04 under Windows 10 Pro.
After commit https://github.com/Microsoft/types-publisher/commit/67c5fe2eac98752800b4c06d2affec951b92340c I can no longer install neither `types-publisher` nor dependent packages (like DefinitelyTyped) under WSL.
I got several different errors while building `node-git`, tried to fix it, made some progress but wasn't able to build it.

Related issue: https://github.com/nodegit/nodegit/issues/1134 (none of the solutions worked for me).

Here's the log I get from `node-git` when trying to build it:
```
vendor/libssh2.target.mk:126: recipe for target 'Release/obj.target/libssh2/vendor/libssh2/src/openssl.o' failed
make: *** [Release/obj.target/libssh2/vendor/libssh2/src/openssl.o] Error 1
make: Leaving directory '/mnt/c/dev/DefinitelyTyped/node_modules/nodegit/build'
gyp
ERR! build error
gyp
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/c/dev/DefinitelyTyped/node_modules/node-gyp/lib/build.js:262:23)
gyp
ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp
ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR!
command "/usr/bin/node" "/mnt/c/dev/DefinitelyTyped/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/mnt/c/dev/DefinitelyTyped/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/mnt/c/dev/DefinitelyTyped/node_modules/nodegit/build/Release"
gyp
ERR! cwd /mnt/c/dev/DefinitelyTyped/node_modules/nodegit
gyp ERR! node -v v10.10.0
gyp ERR!
node-gyp -v v3.8.0
gyp
ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by andy-ms** [comment]
We no longer use node-git.
