### ISSUE TITLE
Question regarding DT package tree testing

### ISSUE THREAD

**Issue by SimonSchick** [Microsoft/types-publisher#488]
Hey @andy-ms @amcasey 

I’ve been wanting to run the test script that tests packages that depend on the ones changed in individual PRs, eg. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/package.json#L20 

Unfortunately I couldn’t find any docs on how to run this locally, every time I do, I get some error about some package not being whitelisted which is not occurring on travis:

```
$ node node_modules/types-publisher/bin/tester/test.js
Clean data
Clean logs
Clean output
# Typing Publish Report Summary
Started at Thu, 27 Sep 2018 23:15:27 GMT
Found 4951 typings folders in ../DefinitelyTyped/types
Error: In ../DefinitelyTyped/types/react-sortable-tree/package.json: Dependency react-dnd not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
    at checkPackageJsonDependencies (\Projects\vendor\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:166:10)
    at \Projects\vendor\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:110:34
    at Generator.next (<anonymous>)
    at fulfilled (\Projects\vendor\DefinitelyTyped\node_modules\types-publisher\bin\lib\definition-parser.js:4:58)
Error: Parsing failed.
    at fail (\Projects\vendor\DefinitelyTyped\node_modules\types-publisher\src\util\util.ts:320:11)
    at ChildProcess.child.on (\Projects\vendor\DefinitelyTyped\node_modules\types-publisher\src\util\util.ts:308:6)
    at ChildProcess.emit (events.js:182:13)
    at finish (internal/child_process.js:797:14)
    at process._tickCallback (internal/process/next_tick.js:61:11
```

Can you perhaps point me to the correct documentation and/or tell me how I can run these tests (with max concurrency) locally?

**Comment by amcasey** [comment]
@RyanCavanaugh might know more.

**Comment by SimonSchick** [comment]
Works now :)
